apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- carts-db.yaml
- carts.yaml
- catalogue-db.yaml
- catalogue.yaml
- federationservice.yaml
- front-end.yaml
#- nextjs-docker.yaml
- orders-db.yaml
- orders.yaml
- payment.yaml
- queue-master.yaml
- rabbitmq.yaml
- session-db.yaml
- shipping.yaml
- user-db.yaml
- user.yaml