apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    name: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apiservice
  template:
    metadata:
      labels:
        name: apiservice
    spec:
      containers:
      - name: server
        image: apiservice
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  labels:
    name: apiservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 32540
  selector:
    name: apiservice