---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federationservice-be
  labels:
    name: federationservice-be
spec:
  replicas: 1
  selector:
    matchLabels:
      name: federationservice-be
  template:
    metadata:
      labels:
        name: federationservice-be
    spec:
      containers:
      - name: federationservice-be
        image: federationservice-be
        env:
        - name: DB_HOST
          value: "federationservice-db.default.svc.cluster.local:5432"
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: shop1
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: federationservice-be
  labels:
    name: federationservice-be
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
  selector:
    name: federationservice-be