---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    name: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hub
  template:
    metadata:
      labels:
        name: hub
    spec:
      containers:
      - name: hub
        image: ui
      - name: be
        image: be
      - name: db
        image: db
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: hub
  labels:
    name: hub
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5173
    nodePort: 32545
  selector:
    name: hub