apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  #- image: carts
  #  context: carts/docker/carts
  #- image: nextjs-docker
  #  context: federationservice
  - image: federationservice
    context: newfederationservice
    docker:
      dockerfile: Dockerfile
  # - image: federationservice-ui
  #   context: federationservice
  #   docker:
  #     dockerfile: Dockerfile-UI
  #     buildArgs:
  #       PUBLIC_IP: "34.79.149.251"
  # - image: federationservice-be
  #   context: federationservice
  #   docker:
  #     dockerfile: Dockerfile-BE
  #     buildArgs:
  #       PUBLIC_IP: "34.79.149.251"
  # - image: federationservice-db
  #   context: federationservice
  #   docker: 
  #     dockerfile: Dockerfile-DB
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
deploy:
  kubectl: {}